### ISSUE TITLE
old syntax?

### ISSUE THREAD

**Issue by jasonwilliams** [matchai/criterion-compare-action#1]
Is the action syntax now out of date?
Seems they're all yaml now

**Comment by matchai** [comment]
This does indeed use the old syntax, but it is still optionally usable.

**Comment by jasonwilliams** [comment]
@matchai not really.

> Support for the HCL syntax in GitHub Actions will be deprecated on September 30, 2019.
https://help.github.com/en/articles/about-github-actions#migrating-github-actions-from-hcl-to-yaml-syntax

I managed to convert it to this:
```yml
on: [pull_request]
name: benchmark pull requests
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: run benchmark
        uses: matchai/criterion-compare-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

using https://github.com/actions/migrate
