### ISSUE TITLE
Run fails with: Command failed: git checkout master

### ISSUE THREAD

**Issue by MidasLamb** [matchai/criterion-compare-action#7]
When ran on a PR it fails with following error:
```
Error: Command failed: git checkout master
error: pathspec 'master' did not match any file(s) known to git
```
But master branch does actually exist.
I have no real experience with github actions but the other actions work fine so.
Extra details [here](https://github.com/MidasLamb/sqlite-varint/runs/647344744?check_suite_focus=true#step:4:9)
I just took the example config.

**Comment by sharksforarms** [comment]
I'm also getting this.

Edit: Found a solution. I added this to the checkout, it fetches all history/branches

```
        with:
          fetch-depth: 0
```

New yaml
```
on: [pull_request]
name: benchmark pull requests
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: run benchmark
        uses: matchai/criterion-compare-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
